119 events
sky-unlimited/wef_2023 pull request #217
Opened 2024-03-14 07:46 UTC by christinasugiono

Events on Landing page
![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/97ca53bd-1910-4a24-b62f-8a384354a4e7)

Index Page
![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/4e5bfcf8-0996-47a6-88d5-aba81e1dda06)

To do:
- Update to a better seed for events
- Update the enum of kind of events (I changed the column name from `type` to `kind` because `type` is a reserved keyword in ruby)

2024-03-14 07:54 UTC, christinasugiono commented on app/views/events/_events.html.erb
> +<%# locals: (events:) %>
this line is about strict locals, which is better and safer when using partials

https://masilotti.com/safer-rails-partials-with-strict-locals/

2024-03-16 02:16 UTC, alexstan67 requested changes

2024-03-16 02:16 UTC, alexstan67 commented on app/views/events/_events.html.erb
> +          <p class="mt-0">📍 <%= "#{event.airport.name} (#{event.airport.icao})" %></p>
Just a last update. Something you cannot know. Not all airports have a "real" ICAO code. For now, we just display the real ones.
So we display the parenthesis and content **only** if:
`event.airport.icao.match?(/^(L|E)...$/)`

2024-03-16 02:19 UTC, alexstan67 commented
Hi @christinasugiono, just a minor change (display only real ICAO codes), result looks amazing! Once you fix it, if you have the rights, you can merge to master!

2024-03-18 09:29 UTC, christinasugiono commented
![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/fb81a4b4-4ae1-461b-b24d-e53bb33d6343)

Last push 💪

2024-03-18 14:30 UTC, alexstan67 approved these changes

2024-03-18 14:31 UTC, alexstan67 commented
To continue with good practices, who has to merge this branch on `master`, me or you?

2024-03-19 01:22 UTC, merged