146 feature blognewsletter
sky-unlimited/wef_2023 pull request #220
Opened 2024-03-18 08:39 UTC by alexstan67

closes#146

- Creation of the Blog/Newsletter index show edit destroy
- Possibility to schedule an email with the current newsletter for next Friday at 16h00 local time
- Responsive design

2024-03-18 08:40 UTC, alexstan67 commented
![image](https://github.com/sky-unlimited/wef_2023/assets/99043399/6d37e6c2-03b2-47ec-98df-5ff5e46dc342)
![image](https://github.com/sky-unlimited/wef_2023/assets/99043399/c5b196ef-bb7d-42ee-8d90-fbb7ab33310c)

2024-03-18 09:08 UTC, christinasugiono requested changes

2024-03-18 09:08 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +</style>
Better move it to `card.scss`

2024-03-18 09:15 UTC, christinasugiono requested changes

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +      <div  id="card"
```suggestion
      <div  class="card"
```

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +</style>
Better move this code to `card.scss` to keep it clean and change the `id` to `class` since its being re-used

```suggestion
<style>
@media only screen and (min-width: 576px) {
  .card {
    margin-left: 10px; 
    min-width: 380px;
    max-width: 380px;
  }
}
</style>
```

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +        <div  id="card-description"
```suggestion
        <div 
```

remove the `id` if there's no use of it

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +        <div  id="card-picture"
```suggestion
        <div 
```

remove the `id` if there's no use of it

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +          <div  id="card-description-author"
```suggestion
        <div 
```

remove the `id` if there's no use of it

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +          <div  id="card-description-title"
```suggestion
        <div 
```

remove the `id` if there's no use of it

2024-03-18 09:15 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +          <div  id="card-description-infos"
```suggestion
        <div 
```

remove the `id` if there's no use of it

2024-03-18 09:18 UTC, alexstan67 commented on app/views/blogs/index.html.erb
> +</style>
Ok for me, but it means this style will be applied on all views having a `class="card"`. It is not what we want...
I try to avoid customizing the components with pages specific needs... But I agree that cards is a kind of exception...
So should I rename `.card` to `.card-blog-index` ?

2024-03-18 09:21 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +</style>
`.card-blog-index` I would prefer. this yes

2024-03-18 09:23 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +  <div id="blogs" class="d-flex flex-wrap">
try consider using grid for displaying these cards, it will look more consistent for the spacing

```suggestion
  .blog-cards {
  }
```

2024-03-18 09:25 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +  <div id="blogs" class="d-flex flex-wrap">
If you try this method, you can remove the `margin` of each card

2024-03-18 11:36 UTC, alexstan67 commented on app/views/blogs/index.html.erb
> +  <div id="blogs" class="d-flex flex-wrap">
Could be indeed interesting, but it doesn't fit neither on large screen or on mobile:
![image](https://github.com/sky-unlimited/wef_2023/assets/99043399/027e0a35-2bef-4f4f-b7c1-804ff98838d7)
I'll skip this one for now.

2024-03-19 01:21 UTC, christinasugiono commented on app/views/blogs/index.html.erb
> +  <div id="blogs" class="d-flex flex-wrap">
you need to add media query for mobile and make the `grid-template-column: 1fr` so it becomes 1 column only, and maybe for medium screen `grid-template-column: 1fr 1fr`

2024-03-21 16:19 UTC, merged