218 pilots refactor
sky-unlimited/wef_2023 pull request #228
Opened 2024-03-21 09:07 UTC by christinasugiono

![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/bb212254-975d-4abc-8084-a55b39430031)

2024-03-21 18:12 UTC, alexstan67 requested changes
It is a tough one! Huge work, well done! I'll pull the branch and proceed to tests asap.

2024-03-21 18:12 UTC, alexstan67 commented on test/fixtures/pilot_certificates.yml
> +  pilot: one
```suggestion
  pilot: regular_pilot
```

2024-03-21 18:12 UTC, alexstan67 commented on test/fixtures/pilot_certificates.yml
> +  pilot: two
```suggestion
  pilot: regular_staff
```

2024-03-21 18:12 UTC, alexstan67 commented on test/fixtures/followers.yml
> +  following: one
```suggestion
  following: two
```

2024-03-21 18:12 UTC, alexstan67 commented on test/fixtures/followers.yml
> +  following: two
```suggestion
  following: one
```

2024-03-22 05:27 UTC, christinasugiono commented on app/assets/stylesheets/pages/_pilot_show.scss
> +@media screen and (max-width: 768px) {
I saw also, I can update it to be mobile first then to follow the existing flow

2024-03-22 05:29 UTC, christinasugiono commented on app/controllers/followers_controller.rb
> +      AuditLog.find_by(target_controller: 'followers', target_id: follow.id).destroy
Its a bit tricky also here since the Follower got destroyed when someone unfollow a person... so the audit log cannot store the `follow.id` since its gone... I'm a bit wondering too if we really need AuditLog for Follow logic since the table on its own is enough to see who follows who at what time 🤔

2024-03-22 05:30 UTC, christinasugiono commented on config/locales/fr.yml
You are right sir! Will add this

2024-03-22 05:37 UTC, christinasugiono commented on db/migrate/20240320061127_create_preferences.rb
> +class CreatePreferences < ActiveRecord::Migration[7.1]
Oh I thought about this too and tried it a bit (but gave up 😅 ), but the thing is some columns and association also being updated with now having `pilots` table and `certificates` table and we have existing data to be moved. 

And when I tried moving and renaming existing table, it was harder to keep it clean when updating it (mostly because of the existing association). If we have time to call I will try to explain it a bit. This way seems more work but in the end I found it easier and cleaner.

2024-03-22 05:39 UTC, christinasugiono commented on db/migrate/20240320061127_create_preferences.rb
> +class CreatePreferences < ActiveRecord::Migration[7.1]
There might be a better way but yeah 😅 This way at least much easier to track, but I do need to clean some tables and columns after making sure all the migration works properly in production env (issue #229)

2024-03-22 05:44 UTC, christinasugiono commented on db/migrate/20240320085052_update_pilot_certificate.rb
True! I will put wrapper on the initial seeds so that they don't run on production env

2024-03-22 06:25 UTC, christinasugiono commented on app/assets/stylesheets/pages/_pilot_show.scss
> +@media screen and (max-width: 768px) {
Wops! I updated this on the #219 PR 😅  But its updated

2024-03-22 06:41 UTC, alexstan67 commented on app/controllers/followers_controller.rb
> +      AuditLog.find_by(target_controller: 'followers', target_id: follow.id).destroy
Ok I agree with you, let's remove the auditLog for followers!

2024-03-22 10:06 UTC, alexstan67 approved these changes

2024-03-22 11:00 UTC, alexstan67 approved these changes

2024-03-22 11:03 UTC, merged