268 refactor cicd setup
sky-unlimited/wef_2023 pull request #273
Opened 2024-04-22 06:42 UTC by christinasugiono

2024-04-23 12:19 UTC, alexstan67 requested changes
Hi Chris, can you have a look at those 4 comments please? Especially the one with `database.yml`...

Thanks!

2024-04-23 12:19 UTC, alexstan67 commented on .gitignore
Why commenting it? I think it is good practice not to show your database.yml

2024-04-23 12:19 UTC, alexstan67 commented on config/database.yml
I do not agree to commit/merge this file... security issue...

2024-04-23 12:19 UTC, alexstan67 commented on db/migrate/20230604172140_create_airports.rb
Why did we change this one? Was for debug?

2024-04-23 12:19 UTC, alexstan67 commented on db/migrate/20240320061458_move_pilot_pref_data.rb
I don't understand this one... Is there a link with CI setup?

2024-04-24 07:00 UTC, christinasugiono commented on config/database.yml
This one, the encrypted file, is okay. Just need to make sure the key not exposed

2024-04-24 07:04 UTC, christinasugiono commented on db/migrate/20230604172140_create_airports.rb
I don't remember changing this one 😅 Do you think it happened as part of the rubocop?

2024-04-24 07:14 UTC, christinasugiono commented on db/migrate/20240320061458_move_pilot_pref_data.rb
`if Object.const_defined? "PilotPref"` this line I added because when I dropped the db and re-migrate it broke... I'm pretty sure because we deleted `PilotPref` model already

2024-04-24 07:14 UTC, christinasugiono commented on .gitignore
This one is needed for the CI/CD to read the database.yml, and its actually needed also usually for deployment on production, as long as the important info are stored inside ENV or credentials

2024-04-24 07:17 UTC, christinasugiono commented on .gitignore
You can also put everything like `db_name` `username` etc also under the ENV file

2024-04-24 07:19 UTC, alexstan67 commented on db/migrate/20230604172140_create_airports.rb
Indeed, strange... I'm currently testing this one to verify no incidence...

2024-04-24 08:20 UTC, alexstan67 approved these changes

2024-04-24 08:21 UTC, merged