239 rebranding
sky-unlimited/wef_2023 pull request #278
Opened 2024-04-30 03:42 UTC by christinasugiono

<img width="1491" alt="Screenshot 2024-04-30 at 11 37 47" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/d4ab2698-d27f-417a-b271-abfd3db85cd8">
<img width="864" alt="image" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/6ae8a8bb-7ff8-422b-a80e-be183708cf8a">
<img width="394" alt="Screenshot 2024-04-30 at 11 41 57" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/b846c379-5e12-4db8-ae65-3612427d24ab">

NEXT STEP:
- New POI icons from Maria ✨

2024-05-05 17:49 UTC, alexstan67 requested changes
It is a HUGE work, well done!
I found small problems mainly on translations, that means that our tests are not efficient enough, I'll work on it (already begun).
- I also saw a problem on `TripRequest#new` when you loading animation appears: The airport search box doesn't seem to have the correct opacity.
- On the `TripSuggestions#index`, the flight duration are not displayed properlly. It works on production. If flight time > 60 minutes, we display in hours and minutes.
- Still on same page, when you take a point of interest on the map, the header's size is way too big.
- On `Airports#show`, personnaly I don't like the different colors depending on the airport_type... I would stick to one color... Or we only stick to accent colors, but no primary for example.
Again, well done for this work! :clap:

2024-05-05 17:49 UTC, alexstan67 commented on app/assets/stylesheets/pages/_console.scss
Console.scss should be removed as not used anymore. Replaced by blazer.

2024-05-05 17:49 UTC, alexstan67 commented on app/assets/stylesheets/pages/_index.scss
>  @import "console";
Delete this line

2024-05-05 17:49 UTC, alexstan67 commented on app/models/trip_request.rb
There is a translation issue in french

2024-05-05 17:49 UTC, alexstan67 commented on app/views/airports/show.html.erb
> +        <p><%= t('airport.show.no_events') %></p>
I think this is the missing translation

2024-05-05 17:49 UTC, alexstan67 commented on app/views/trip_requests/_form.html.erb
> +        <label class="form-label text-small text-uppercase"><%= t('trip_request.categories.transportations').upcase %></label>
The translations are missing for fr I think

2024-05-06 01:01 UTC, christinasugiono commented on app/views/trip_requests/_form.html.erb
> +        <label class="form-label text-small text-uppercase"><%= t('trip_request.categories.transportations').upcase %></label>
For the `trip_suggestions#index` display time, is this what you meant? 
<img width="1179" alt="image" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/ff5ffbbf-ae8f-415b-8114-a5b78b6d75f4">

2024-05-06 08:23 UTC, alexstan67 approved these changes

2024-05-07 07:52 UTC, merged