233 analytics tool
sky-unlimited/wef_2023 pull request #284
Opened 2024-05-08 08:58 UTC by christinasugiono

![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/96cb42bd-d8a3-4ce1-a246-5e49a8ebca74)

closes #233

2024-05-13 09:11 UTC, christinasugiono commented
Newly created article automatically included in the statistic :D

2024-05-20 06:00 UTC, christinasugiono commented
**How To Add New Tracker**

Put this code in the controller of the page you want to track:

- With properties
`ahoy.track "Viewed Blog", blog_id: id`
- Without properties
`ahoy.track "Viewed Page"`

2024-05-23 01:29 UTC, christinasugiono commented
## Statistics (Blazer)
### Total visitor count
```
SELECT 
    name,
    COUNT(*)
FROM ahoy_events
GROUP BY name
```

### All blogs visitor count
```
WITH blog_visit_count AS (
    SELECT (properties->>'blog_id')::integer AS blog_id,
           COUNT(*) AS view_count
    FROM ahoy_events
    WHERE name = 'Viewed blog'
    GROUP BY (properties->>'blog_id')::integer
)

SELECT b.title, bvc.view_count
FROM blogs b
LEFT JOIN blog_visit_count bvc ON b.id = bvc.blog_id;
```

### Pages visitor growth
```
SELECT 
    date_trunc({period}, time)::date AS period, 
    name,
    COUNT(*) AS visitor_count 
FROM ahoy_events 
GROUP BY period, name
ORDER BY period
```

### All blogs visitor growth
```
WITH blog_monthly_visit AS (
    SELECT 
        date_trunc({period}, time)::date AS period,
        (properties->>'blog_id')::integer AS blog_id,
        COUNT(*) AS view_count
    FROM ahoy_events
    WHERE name = 'Viewed blog'
    GROUP BY period, blog_id
    ORDER BY period
)

SELECT
    period,
    b.title,
    view_count
FROM blog_monthly_visit bmv
LEFT JOIN blogs b
ON b.id = bmv.blog_id
```

### Blog visitor growth
```
WITH blog_monthly_visit AS (
    SELECT 
        date_trunc({period}, time)::date AS period,
        (properties->>'blog_id')::integer AS blog_id,
        COUNT(*) AS view_count
    FROM ahoy_events
    WHERE name = 'Viewed blog'
    GROUP BY period, blog_id
    ORDER BY period
)

SELECT
    period,
    b.title,
    view_count
FROM blog_monthly_visit bmv
LEFT JOIN blogs b
ON b.id = bmv.blog_id
WHERE b.id = {blog}
```

2024-05-23 02:49 UTC, christinasugiono commented
To test the `geolocation` of `Ahoy::Visit`

- Run `ngrok` [`documentation`](https://ngrok.com/docs/getting-started/)
   `localhost` won't give enough information on the IP address for geocode, so we use `ngrok`
- Run `rake solid_queue:start`
- Visit landing page/trip request/blogs

2024-05-26 05:34 UTC, alexstan67 requested changes
I have only 3 general comments:
- We want to activate the local geocoding of countries (not cities): https://www.rubydoc.info/gems/ahoy_matey/5.1.0#local-geocoding
  - it implies to update the `Readme.md`
- We don't want to track users, so we remove the links between visits, events and users (GDPR)
- I'm not sure why you made modification on Blogs?
Happy to discuss, ++

2024-05-26 05:34 UTC, alexstan67 commented on app/models/ahoy/event.rb
Is this class necessary?

2024-05-26 05:34 UTC, alexstan67 commented on app/models/ahoy/visit.rb
Is this class necessary?

2024-05-26 05:34 UTC, alexstan67 commented on app/views/blogs/_form.html.erb
Why did you change this one? For example, if you edit a drafted blog, the check boxes below disappeared... Not working anymore...

2024-05-26 05:34 UTC, alexstan67 commented on config/locales/default_en.yml
> +    statistic: Statistics
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on config/initializers/ahoy.rb
> +  def authenticate(data)
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on config/initializers/ahoy.rb
> +    # disables automatic linking of visits and users
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on config/initializers/ahoy.rb
> +  end
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on config/locales/default_fr.yml
> +    statistic: "Statistiques"
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on db/migrate/20240508075747_create_ahoy_visits_and_events.rb
> +      t.references :user
```suggestion
```

2024-05-26 05:34 UTC, alexstan67 commented on db/migrate/20240508075747_create_ahoy_visits_and_events.rb
> +      t.string :app_version
```suggestion
      #t.string :app_version
```

2024-05-26 05:34 UTC, alexstan67 commented on db/migrate/20240508075747_create_ahoy_visits_and_events.rb
> +      t.string :os_version
```suggestion
      #t.string :os_version
```

2024-05-26 05:34 UTC, alexstan67 commented on db/migrate/20240508075747_create_ahoy_visits_and_events.rb
> +      t.string :platform
```suggestion
      #t.string :platform
```

2024-05-26 05:34 UTC, alexstan67 commented on db/migrate/20240508075747_create_ahoy_visits_and_events.rb
> +      t.references :user
```suggestion
      #t.references :user
```

2024-05-26 05:34 UTC, alexstan67 commented on test/system/users_test.rb
Ok, but in this case should we replace it with a controller users test?

2024-05-26 05:34 UTC, alexstan67 commented on app/models/user.rb
> +  has_many :visits, class_name: 'Ahoy::Visit'
```suggestion
```

2024-05-27 09:10 UTC, christinasugiono commented on app/models/ahoy/event.rb
I assume yes, because its generated during the gem ahoy setup rails generate ahoy:install :D

2024-05-30 17:58 UTC, alexstan67 approved these changes

2024-05-30 18:05 UTC, alexstan67 reviewed
Let's merge!

2024-05-30 18:05 UTC, alexstan67 commented on test/system/users_test.rb
What do we do with this one?

2024-05-30 18:05 UTC, alexstan67 commented on app/views/blogs/_form.html.erb
Is there a link with analytics tools? Is it commit from the fix branch?

2024-05-30 18:09 UTC, merged