225 rating and comments
sky-unlimited/wef_2023 pull request #286
Opened 2024-05-16 09:03 UTC by christinasugiono

Only a user that visited the airport can contribute to `rating` and `comments`

![image](https://github.com/sky-unlimited/wef_2023/assets/74747669/4a859cf9-d809-41a5-935c-584c7b8bb7ca)

clsoes #225

2024-05-21 08:57 UTC, alexstan67 reviewed
Hi @christinasugiono, here are some comments:
- It seems not possible to add a review on our homebase airport
- Once the review is done, and the page is loaded, we have a eager loading issue
- If your give a rating of 3 for example, than in the comment, you I guess you should also display 2 "dark" stars as well, no?

2024-05-21 13:47 UTC, alexstan67 requested changes
Hi @christinasugiono, I took time to review. You did crazy work, I would not have been able to implement this I think... Good job, but let's discuss some points tomorrow during meeting!

2024-05-21 13:47 UTC, alexstan67 commented on app/assets/stylesheets/components/_modals.scss
Very good!

2024-05-21 13:47 UTC, alexstan67 commented on app/controllers/airports_controller.rb
> +                       .includes(visited_airport: {
I have an eager loading alert here, but not confident enough to remove it:
````bash
[2024-05-21 15:00:50 +0200] user: alex
GET /airports/2563
AVOID eager loading detected
  Pilot => [:user, :airport]
  Remove from your query: .includes([:user, :airport])
Call stack
  /home/alex/github/sky-unlimited/wef_2023/app/views/ratings/_ratings.html.erb:34:in `_app_views_ratings__ratings_html_erb___1299818406138423748_41100'
  /home/alex/github/sky-unlimited/wef_2023/app/views/airports/show.html.erb:313:in `block in _app_views_airports_show_html_erb___388856586667220054_40680'
  /home/alex/github/sky-unlimited/wef_2023/app/views/airports/show.html.erb:312:in `_app_views_airports_show_html_erb___388856586667220054_40680'
  /home/alex/github/sky-unlimited/wef_2023/app/controllers/application_controller.rb:19:in `switch_locale'


[2024-05-21 15:00:50 +0200] user: alex
GET /airports/2563
AVOID eager loading detected
  Rating => [:visited_airport]
  Remove from your query: .includes([:visited_airport])
Call stack
  /home/alex/github/sky-unlimited/wef_2023/app/views/ratings/_ratings.html.erb:34:in `_app_views_ratings__ratings_html_erb___1299818406138423748_41100'
  /home/alex/github/sky-unlimited/wef_2023/app/views/airports/show.html.erb:313:in `block in _app_views_airports_show_html_erb___388856586667220054_40680'
  /home/alex/github/sky-unlimited/wef_2023/app/views/airports/show.html.erb:312:in `_app_views_airports_show_html_erb___388856586667220054_40680'
  /home/alex/github/sky-unlimited/wef_2023/app/controllers/application_controller.rb:19:in `switch_locale'
````

2024-05-21 13:47 UTC, alexstan67 commented on app/controllers/ratings_controller.rb
> +      @ratings = @visited_airport.airport.ratings
I don't know if there is also an eager loading problem here...

2024-05-21 13:47 UTC, alexstan67 commented on app/views/airports/show.html.erb
> +      <h1><%= NormalizeCountry(@airport.country.code, :to => :emoji) %> <br> <%= @airport.display_name %></h1>
Seems clever to proceed so, it brings consistency through all application. But where is defined the method `display_name` ?

2024-05-21 13:47 UTC, alexstan67 commented on app/views/preferences/edit.html.erb
> +    <%= form_for @preference, url: edit_preferences_path, data: { turbo: false } do |f| %>
I have this error:
No route matches [PATCH] "/preferences/edit"

2024-05-21 13:47 UTC, alexstan67 commented on app/views/preferences/edit.html.erb
> +    <%= form_for @preference, url: edit_preferences_path, data: { turbo: false } do |f| %>
It also means our controller tests are not good enough for this one :smile:

2024-05-21 13:47 UTC, alexstan67 commented on config/environment.rb
Should it not be present in `config/environments/production.rb` ?

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +      reviews: Reviewaire
```suggestion
      reviews: Revues
```

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +      ratings: Évaluation
```suggestion
      ratings: Évaluations
```

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +      new_review: Nouveau Reviewaire
```suggestion
      new_review: Nouvelle évaluation
```

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +      no_reviews: Pas de reviewaires. Soyez le premier!
```suggestion
      no_reviews: Pas d'évaluations. Soyez le premier!
```

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +      more_reviews: Afficher tous les %{count} reviewaires
```suggestion
      more_reviews: Afficher toutes les %{count} évaluations
```

2024-05-21 13:47 UTC, alexstan67 commented on config/locales/fr.yml
> +    title: Reviewaires pour %{airport}
```suggestion
    title: Evaluations pour %{airport}
```

2024-05-21 13:47 UTC, alexstan67 commented on test/fixtures/ratings.yml
> +invalid_rating:
Maybe let's discuss it, I used to make the same invalid tests, but it has no sense I think to insert a bad record in database... I think it should be tested with a creation having n bad values...

2024-05-21 13:47 UTC, alexstan67 commented on test/controllers/ratings_controller_test.rb
I think we should write 1 or 2 tests, WDYT? At least is it accessible when not been there? Accessible when visited?

2024-05-21 13:47 UTC, alexstan67 commented on config/routes.rb
Should we add an entry in the menu only in `development` environment? I didn't know this, it's interesting, but I don't understand how it works :disappointed:

2024-05-21 13:47 UTC, alexstan67 commented on app/views/ratings/create.turbo_stream.erb
Amazing, can you explain me how it works?

2024-05-22 03:46 UTC, christinasugiono commented on app/controllers/airports_controller.rb
> +                       .includes(visited_airport: {
I cannot 100% fix this, one scenario still give a warning which is when the user creates the first comment for the airport. After there's another comment given from another user, the warning is gone.

I tried following the suggestion from bullet gem, but in the suggestion is circling.. 😮‍💨  First it asked me to add the `.includes` then after I add, it asked me to remove it....

2024-05-22 03:48 UTC, christinasugiono commented on app/views/airports/show.html.erb
> +      <h1><%= NormalizeCountry(@airport.country.code, :to => :emoji) %> <br> <%= @airport.display_name %></h1>
It's a method from `airport.rb` model, I feel like I repeated this display name to many times, better create a method for it :D

2024-05-22 03:49 UTC, christinasugiono commented on app/views/preferences/edit.html.erb
> +    <%= form_for @preference, url: edit_preferences_path, data: { turbo: false } do |f| %>
<img width="1284" alt="image" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/07eec35a-ce0b-4eeb-b32c-f696bde85f45">

I think we need to check this together then, cause on my side its okay....

2024-05-22 05:36 UTC, christinasugiono commented on config/routes.rb
Good idea! I added it in the menu for `admin` and `development` env

<img width="1285" alt="Screenshot 2024-05-22 at 13 32 52" src="https://github.com/sky-unlimited/wef_2023/assets/74747669/ed478b8b-cd81-4b93-89f3-bace9aa43479">

2024-05-22 05:36 UTC, christinasugiono commented on config/environment.rb
Maybe, but it was there already before, so was not sure if I should move it 😅

2024-05-22 09:46 UTC, alexstan67 approved these changes

2024-05-22 09:46 UTC, merged